language: objective-c
osx_image: xcode9.2
rvm:
- 2.2

env:
- TRAVIS_TAG="Deploy-2017.4.33f" PROJECT_NAME="VirtualModeller" UNITY_PROJECT_PATH="Virtual Modeller"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

before_install:
- chmod a+x ./travis/*.sh

install:
- ./travis/install.sh

script:
- ./travis/run-tests.sh
- ./travis/build.sh
